version: '3.7'

networks:
  hdbnet:
    driver: bridge

services:
  hdbpp-database:
    image: mariadb:10.8
    networks:
      - hdbnet
    ports:
      - "3306:3306"
    hostname: hdbpp-db
    container_name: hdbpp-db
    environment:
      - MARIADB_ROOT_PASSWORD=dbroot
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./database/hdbpp:/var/lib/mysql
  hdbpp-cm:
    image: hdbpp-cm:latest
    hostname: hdbpp-cm
    container_name: hdbpp-cm
    networks:
      - hdbnet
    ports:
      - "45001:45001"
    environment:
      - TANGO_HOST=curie.maxi.lab:10000
      - INSTANCE_NAME=2
      - OMNIORB_PORT=45001
      - OMNIORB_PUBLISH=curie.maxi.lab
    extra_hosts:
      - "host.docker.internal:host-gateway"
  hdbpp-es:
    image: hdbpp-es:latest
    hostname: hdbpp-es
    container_name: hdbpp-es
    networks:
      - hdbnet
    ports:
      - "45002:45002"
    environment:
      - TANGO_HOST=curie.maxi.lab:10000
      - INSTANCE_NAME=2
      - OMNIORB_PORT=45002
      - OMNIORB_PUBLISH=curie.maxi.lab
    extra_hosts:
      - "host.docker.internal:host-gateway"


