version: '3.7'

networks:
  hdbnet:
    driver: bridge

services:
  hdbpp-database:
    image: mariadb:10.8
    networks:
      - hdbnet
    ports:
      - "3307:3306"
    hostname: hdbpp-db
    container_name: hdbpp-db
    environment:
      - MARIADB_ROOT_PASSWORD=dbroot
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - /data/hdbpp:/var/lib/mysql
  hdbpp-cm:
    image: hdbpp-cm:latest
    hostname: hdbpp-cm
    restart: always
    container_name: hdbpp-cm
    networks:
      - hdbnet
    ports:
      - "45001:45001"
    environment:
      - TANGO_HOST=curie.maxi.lab:10000
      - INSTANCE_NAME=2
      - OMNIORB_PORT=45001
      - OMNIORB_PUBLISH=curie.maxi.lab
    extra_hosts:
      - "host.docker.internal:host-gateway"
  hdbpp-es:
    image: hdbpp-es:latest
    hostname: hdbpp-es
    restart: always
    container_name: hdbpp-es
    networks:
      - hdbnet
    ports:
      - "45002:45002"
    environment:
      - TANGO_HOST=curie.maxi.lab:10000
      - INSTANCE_NAME=2
      - OMNIORB_PORT=45002
      - OMNIORB_PUBLISH=curie.maxi.lab
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - hdbpp-database
  egiga2m:
    image: webdevops/php-apache:latest
    hostname: egiga2m
    container_name: egiga2m
    networks:
      - hdbnet
    ports:
      - "80:80"
    volumes:
      - ./eGiga2m/:/app/
      - ./conf/hdbpp_conf.php:/app/lib/service/hdbpp_conf.php
      - ./conf/egiga2m_conf.js:/app/egiga2m_conf.js

