version: '3.7'

### Make sure environment variables in .env file are correct!

networks:
  hdbpp:

services:
  hdbpp-database:
    image: mariadb:10.8
    networks:
      - hdbpp
    ports:
      - "3307:3306"
    hostname: hdbpp-db
    container_name: hdbpp-db
    environment:
      - MARIADB_ROOT_PASSWORD=dbroot
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ${DATAFOLDER}:/var/lib/mysql

  hdbpp-cm:
    build: ./hdbpp-cm
    hostname: hdbpp-cm
    restart: always
    container_name: hdbpp-cm
    networks:
      - hdbpp
    ports:
      - "45001:45001"
    environment:
      - TANGO_HOST=${TANGO_HOST}
      - INSTANCE_NAME=1
      - OMNIORB_PORT=45001
      - OMNIORB_PUBLISH=${OMNIORB_PUBLISH}
    # uncomment and edit if your docker host and tango host are the same machine!
    extra_hosts:
      - "celsius.evaporator.lab:host-gateway"

  hdbpp-es:
    build: ./hdbpp-es
    hostname: hdbpp-es
    restart: always
    container_name: hdbpp-es
    networks:
      - hdbpp
    ports:
      - "45002:45002"
    environment:
      - TANGO_HOST=${TANGO_HOST}
      - INSTANCE_NAME=1
      - OMNIORB_PORT=45002
      - OMNIORB_PUBLISH=${OMNIORB_PUBLISH}
    # uncomment and edit if your docker host and tango host are the same machine!
    extra_hosts:
      - "celsius.evaporator.lab:host-gateway"
    depends_on:
      - hdbpp-database

  egiga2m:
    build: ./eGiga2m
    hostname: egiga2m
    container_name: egiga2m
    networks:
      - hdbpp
    ports:
      - "80:80"

