CREATE DATABASE IF NOT EXISTS hdbpp;

USE hdbpp;
GRANT SELECT,INSERT,UPDATE,DELETE,EXECUTE ON hdbpp.* TO 'hdbpprw'@'%' IDENTIFIED BY 'hdbpprw';
GRANT SELECT ON hdbpp.* TO 'hdbppro'@'%' IDENTIFIED BY 'hdbppro';
FLUSH PRIVILEGES;
